CREATE TABLE Type_2 (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  name_2 varchar(45) NOT NULL UNIQUE,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;